#!/bin/sh

PATH="$PATH:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin"
hash -r

# URL of your Let's Encrypt Certificate (this will check the /etc/letsencrypt/live/$URL directory in your server)
# Also the URL of your BitWarden's SSL directory (e.g., /opt/bitwarden/bwdata/ssl/$URL/)
URL=bitwarden.example.com

# Location of the logfile
LOGFILE=/opt/bitwarden/renew_cert.log

# Date for logging (e.g. 2019-Nov-14-10:49)
DATE_LOG=$(date +%4Y-%b-%d-%H:%M)

# Service Account Username
SERVICE_ACCOUNT=bitwarden

# Location of the cert files generated by certbot
LE_PRIVATE_KEY=/etc/letsencrypt/live/$URL/privkey.pem
LE_FULLCHAIN=/etc/letsencrypt/live/$URL/fullchain.pem
LE_CA_FILE=/etc/letsencrypt/live/$URL/chain.pem

# Location to store the certificates in BitWarden's environment
BITWARDEN_SSL_PRIVATE_KEY=/opt/bitwarden/bwdata/ssl/$URL/privkey.pem
BITWARDEN_SSL_FULLCHAIN=/opt/bitwarden/bwdata/ssl/$URL/fullchain.pem
BITWARDEN_SSL_CA_FILE=/opt/bitwarden/bwdata/ssl/$URL/chain.pem

# Stop script if not ran as root or sudoer
if [ "$(id -u)" != "0" ]; then
        echo "Must run as root"
        exit 255
fi

# Run certbot to renewal our SSL Certificates
echo "$DATE_LOG: Attempting to renew cert with Certbot" >> $LOGFILE
# this line will require an update if you use an ACME Challenger.
/usr/bin/certbot renew


# If one of the chain/perm files were renewed in the last 24 hours, begin replacing process.
if [ $(/usr/bin/find $LE_FULLCHAIN -mmin -1440 2>/dev/null) ];then

        # We can replace the cert, begin process.
        echo "$DATE_LOG: We can replace the cert!" >> $LOGFILE

        # Insert code to copy certificates to location
        echo "$DATE_LOG: Copying $LE_PRIVATE_KEY to $BITWARDEN_SSL_PRIVATE_KEY" >> $LOGFILE
        yes | cp -Lf $LE_PRIVATE_KEY $BITWARDEN_SSL_PRIVATE_KEY

        echo "$DATE_LOG: Copying $LE_FULLCHAIN to $BITWARDEN_SSL_FULLCHAIN" >> $LOGFILE
        yes | cp -Lf $LE_FULLCHAIN $BITWARDEN_SSL_FULLCHAIN

        echo "$DATE_LOG: Copying $LE_CA_FILE to $BITWARDEN_SSL_CA_FILE" >> $LOGFILE
        yes | cp -Lf $LE_CA_FILE $BITWARDEN_SSL_CA_FILE

        echo "$DATE_LOG: Giving ownership of cert files to service account $SERVICE_ACCOUNT" >> $LOGFILE
        /usr/bin/sudo chown $SERVICE_ACCOUNT $BITWARDEN_SSL_PRIVATE_KEY $BITWARDEN_SSL_FULLCHAIN $BITWARDEN_SSL_CA_FILE

        # Restart BitWarden
        echo "$DATE_LOG: Restarting $URL." >> $LOGFILE
        /usr/bin/sudo -u $SERVICE_ACCOUNT /opt/bitwarden/bitwarden.sh restart

else
        echo "$DATE_LOG: The cert isn't ready to be renewed." >> $LOGFILE
fi
